### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by spiroski** [codex-project/codex#13]
Hello, we were thinking about building something like this on our team. I like how codex is working, but one feature we need is authentication.
 We have some documentation that is internal to us, and we'd like to basically have accounts that would let us manage access to certain parts of it.
Do you think authentication is something that might benefit this project, and are you interested on working on that? I work with Laravel as well, so if you approve this feature, I will try to implement it when I have time.

**Comment by kaidesu** [comment]
Going to close this as Laravel provides this out of the box.
