### ISSUE TITLE
Turn this into a package

### ISSUE THREAD

**Issue by franzliedke** [codex-project/codex#14]
It would be cool if we could integrate Codex into existing Laravel apps.

Can you turn this into a package instead of a standalone app?

**Comment by zoltanpeto** [comment]
Hi, 

I've recommended the same in the discussion on laracasts.com, probably it's not being followed. 

It sounds like a very useful change to me, codex could be split into two repositories, one containing the "framework", the other the app skeleton. Similar to how Laravel is built: laravel/laravel contains a skeleton that can be used with composer create-project to init a new app, this would then require illuminate/framework that provides all the goodness of laravel. 

If Codex was done the same way, it would be pretty easy to integrate with existing Laravel apps, making a lot more things possible, like authenticating and authorizing by the container app, etc.

I have limited open source time right now, but would be happy to contribute to this as I could make much more use of the project if I could integrate it into my existing apps.

**Comment by franzliedke** [comment]
If I choose to use this for FluxBB, I can help in working on this. =)

**Comment by kaidesu** [comment]
I saw your reply on [Laracasts](https://laracasts.com/discuss/channels/general-discussion/codex-a-weekend-laravel-project-to-help-with-documentation), and replied, but I'll continue the discussion here as it's central to the request.

I've been thinking about this more, and it is something I'd like to do (even before Laravel 5 comes out). I understand the needs you two have as well as possibly many other developers looking into using Codex for their own needs. I'll need to work out the repository situation as I might rename this current repository to something like `codex-app` and creating a new `codex` repository for the package.

I'll update this ticket once I have some more information, but in conclusion, this is a step in the right direction that I'd like to make.

**Comment by franzliedke** [comment]
Cool. I can help you with the re-structuring, I did the same for FluxBB. A core that can be integrated with Laravel apps, and a stand-alone app that bundles everything.

That said, you should probably [create an organization](http://fabien.potencier.org/article/75/about-personal-github-accounts) for this project. =)

**Comment by kaidesu** [comment]
Great article, I'll take it into consideration, thanks!

**Comment by kaidesu** [comment]
@franzliedke & @zoltanpeto as you can probably easily see, I've migrated Codex to it's own GitHub organization: [codexproject](https://github.com/codexproject). I'll be looking into working on extracting the core functionality that makes up codex into a **core** Codex Laravel package once v1.1.0 is released (which is very soon).

Once I get the ball rolling on that, I'd be more than happy to accept any feedback and/or contributions!

:+1:

**Comment by kaidesu** [comment]
@franzliedke & @zoltanpeto [The core package can be found here](https://packagist.org/packages/codexproject/core).

Thanks to @happyDemon for getting the ball rolling on this!

**Comment by franzliedke** [comment]
I like how it says "The Laravel framework" on Packagist. ;)

**Comment by kaidesu** [comment]
Ha, that needs to be updated.

Edit: and updated.
