### ISSUE TITLE
Caching can not work

### ISSUE THREAD

**Issue by franzliedke** [codex-project/codex#23]
I just looked at the code of the repository and discovered code like this:

``` php
return $this->cached("$manual.$version.toc",
                Markdown::parse($this->files->get($tocFile), $manual.'/'.$version));
```

The second argument is passed to Laravel's `Cache::remember()`. Since it is already evaluated (and therefore called) in this piece of code, there is absolutely no gain in caching this value - in fact, there's a little bit of overhead from storing the value in the cache.

You need to pass a Closure for this to have any effect.

**Comment by kaidesu** [comment]
I removed this from Codex 2.0 (which is using the core package and still in development) - I'm going to leave it up to the developer to implement caching for their own application.
