### ISSUE TITLE
Change markdown meta notation and parsing

### ISSUE THREAD

**Issue by RobinRadic** [codex-project/codex#30]
Consider changing the way the meta notation and parsing is done. Here's a quick example of what i mean:

From:

``` markdown
/*
Title:  This is a meta title
Author: This is me
*/

### Hellooooooo
Welcome
```

To:

``` md
<!---
title:  This is a meta title
author: This is me
and:
  this:
    - is
    - yaml
-->

### Hellooooooo
Welcome
```

By changing:
`\Codexproject\Core\Markdown`
to:

``` php
// removing of 'meta' is not required anymore. <!--- is valid markdown docblock -->.
// enables the markdown files to be viewed/rendered normally everywhere, inc github
// the 'meta' should be YAML and then be parsed into an php array
class Markdown
{
    public static function parse($text, $pathPrefix = '')
    {        
        $basePath = url('/' . ltrim($pathPrefix, '/'));
        $rendered = (new Parsedown)->text($text);
        //.....
    }

    /* remove: public static function removeMeta($content)*/

    public static function parseMeta($content)
    {
        $pattern = '/<!---\n([\w\W]*?)\n-->/';
        preg_match($pattern, $content, $matches);
        if ( count($matches) > 1 )
        {
            return \Symfony\Component\Yaml\Yaml::parse($matches[1]);
        }
        return [];
    }
}
```

**Comment by kaidesu** [comment]
Thanks, I will definitely do this. I know there are a few issues with the way that I have it set up currently.

**Comment by happyDemon** [comment]
Why not force a codex.json file in the doc root?
it's easy to write for developers and easy to find and parse for Codex, no?

**Comment by kaidesu** [comment]
I'm not sure what you mean, @happyDemon? This would be for individual pages. Why would you want to have that all lumped into a single file?

**Comment by happyDemon** [comment]
oh, I thought this was on a per-doc basis, instead of on a per-page basis.
I meant like composer has a composer.json file for every project.

Anyway, seems unneeded, now that you've told me ^^

**Comment by kaidesu** [comment]
:+1: no worries
