### ISSUE TITLE
I really love the theme you have in your website http://codex.caffeinated.ninja, any way to get it

### ISSUE THREAD

**Issue by rohithmeethal** [codex-project/codex#31]
I do like the default theme you have in this repository but the http://codex.caffeinated.ninja theme looks superb and i like the nanoscroll part, is there any way to get that theme ?

Thanks for the codex work, now I host all the documentation on my machine itself, fast and easy to every thing in one place :)

**Comment by rohithmeethal** [comment]
Never mind, I have made it look that way, was easy to work with your clean code :)

**Comment by kaidesu** [comment]
:+1:
