### ISSUE TITLE
Couldn't get it installed

### ISSUE THREAD

**Issue by Nebucatnetzer** [codex-project/codex#33]
I tried today to install codex.
It failed while executing "php composer.phar install" 
Ubuntu 14.04
Here's the terminal output:

root@testserver:/var/www/doku# php composer.phar install            Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.                                                       - Installing erusev/parsedown (1.1.1)                                 Downloading: 100%                                                 - Installing react/promise (v2.1.0)                                   Downloading: 100%
- Installing guzzlehttp/streams (3.0.0)
  Downloading: 100%  
- Installing guzzlehttp/ringphp (1.0.3)
  Downloading: 100%
- Installing guzzlehttp/guzzle (5.0.3)
  Downloading: 100%
- Installing symfony/process (v2.5.6)
  Downloading: 100%
- Installing symfony/options-resolver (v2.5.6)
  Downloading: 100%
- Installing kzykhys/git (dev-master 8b3ee31)
  Downloading: 100%
- Installing symfony/translation (v2.5.6)
  Downloading: 100%
- Installing symfony/security-core (v2.5.6)
  Downloading: 100%
- Installing symfony/routing (v2.5.6)
  Downloading: 100%
- Installing symfony/http-foundation (v2.5.6)
  Downloading: 100%
- Installing symfony/event-dispatcher (v2.5.6)
  Downloading: 100%
- Installing symfony/debug (v2.5.6)
  Downloading: 100%
- Installing psr/log (1.0.0)
  Downloading: 100%
- Installing symfony/http-kernel (v2.5.6)
  Downloading: 100%
- Installing symfony/finder (v2.5.6)
  Downloading: 100%
- Installing symfony/dom-crawler (v2.5.6)
  Downloading: 100%
- Installing symfony/css-selector (v2.5.6)
  Downloading: 100%
- Installing symfony/console (v2.5.6)
  Downloading: 100%
- Installing symfony/browser-kit (v2.5.6)
  Downloading: 100%
- Installing swiftmailer/swiftmailer (v5.3.0)
  Downloading: 100%
- Installing stack/builder (v1.0.2)
  Downloading: 100%
- Installing patchwork/utf8 (v1.1.26)
  Downloading: 100%
- Installing nesbot/carbon (1.13.0)
  Downloading: 100%
- Installing jeremeamia/superclosure (1.0.1)
  Downloading: 100%

monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)                                         monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)                            monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)            laravel/framework suggests installing doctrine/dbal (Allow renaming columns and dropping SQLite columns.)                               Generating autoload files                                           > php artisan clear-compiled                                        Mcrypt PHP extension required.
Script php artisan clear-compiled handling the post-install-cmd event returned with an error
  [RuntimeException]
  Error Output:                                                     install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]

**Comment by kaidesu** [comment]
Looks like you need the Mcrypt PHP extension installed. If you're using Ubuntu, you can run the following:

```
sudo apt-get install php5-mcrypt
```

This isn't an error with Codex, but rather with your OS not meeting the requirements of Laravel.

**Comment by Nebucatnetzer** [comment]
I have it installed. However your hint might help solving. It seems that other people have experienced similar problems with mcrypt. I'll research some more.

**Comment by Nebucatnetzer** [comment]
This fixes this problem:http://askubuntu.com/questions/460837/mcrypt-extension-is-missing-in-14-04-server-for-mysql

**Comment by kaidesu** [comment]
:+1:
