### ISSUE TITLE
Route / Project issue

### ISSUE THREAD

**Issue by Pathsofdesign** [codex-project/codex#6]
Hey there, I was wondering if this is stable enough to get rolling for some local documentation. After installing, I created a project with the artisan command however I'm having some issues with the `codex.document` route.

```PHP
->where('projectSlug', '^((?!' . \Codex\Codex\Extensions::getExcludedProjectNames(true) . ').*?)$')
```

When I go with this, I receive a 404:
```
NotFoundHttpException in RouteCollection.php line 161:
```

However, if I change to read:

```
->where('projectSlug', 'myProjectName')
```

It at least tries to fetch the index.md in my resources/docs/myProjectName/master/ directory but it says the file can't be found even though it's actually there.

```
FileNotFoundException in FilesystemAdapter.php line 58:
/home/vagrant/codex-new/resources/docs/myProjectName/master/index.md
```

Any help would greatly be appreciated, thank you!

**Comment by kaidesu** [comment]
You'll want to use the legacy codex app until we get this in a state that's stable for use~

https://github.com/codex-project/legacy-codex
